version: "3.8"

services:
  wg-easy:
    environment:
      - WG_HOST=tudominio.es #tu ip pública / dominio
      - PASSWORD= # la contraseña para el panel (opcional)
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg
    volumes:
      - './wg-easy:/etc/wireguard'
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      red-privada:
        ipv4_address: 10.8.1.2

  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      - WEBPASSWORD= # la contraseña para el panel (opcional)
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8050:80/tcp"
    restart: unless-stopped
    networks:
      red-privada:
        ipv4_address: 10.8.1.3

networks:
  red-privada:
    ipam:
      config:
        - subnet: 10.8.1.0/24
