version: "3.8"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - './config:/config'
    ports:
      - 8001:80
      - 8002:443
    restart: unless-stopped