# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark #light/dark Elige el tema que más te guste
jwt_secret: F67D1D49C4E983ECF3C2255C655EC19D707CE74C2A88CCBE2F60FDC2DDD4AD4D # https://www.grc.com/passwords.htm - copia '64 random hexadecimal characters (0-9 and A-F)'

default_redirection_url: https://google.com/ #Aqui hará una redireccion si no existe ningun dominio en nuestro archivo

server: # No tocar nada
  host: 0.0.0.0 
  port: 9091
  path: ""
  buffers:
    read: 4096
    write: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log: # No tocar nada
  level: debug

totp:
  issuer: tudominio.es # Debes poner tu dominio
  period: 30
  skew: 1

authentication_backend: # No tocar nada
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password: #https://argon2.online/
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: bypass # las políticas pueden ser: deny, one_factor, two_factor y bypass
  rules:
    ## bypass rule
    - domain:
        - "auth.tudominio.es" # Debes añadir tu subdominio creado SOLO para authelia
      policy: bypass # Siempre bypass
    # Nuevos dominios
    - domain:
        - "pagina1.tudominio.com" # nombre completo del dominio o página
      policy: two_factor          # política que quieras aplicar
      networks:                   # opcional, en caso de que quieras que solo se pueda acceder a través de cierta red.
        - 192.168.1.0/24
    - domain:
        - "*.tudominio.com"       # el * significa que la política afectará a todos los dominios que contengan '.tudominio.com'
      policy: bypass
    #Cada vez que modifiquemos un dominio, hay que parar y arrancar el contenedor de authelia para que ejecute los cambios.
session:
  name: authelia_session
  secret: 9C29E5C7E7BAF288E2E730B1685733CDB46E8184BE7F3D46F96AFD9DE79241E9 # https://www.grc.com/passwords.htm - copia '64 random hexadecimal characters (0-9 and A-F)':
  expiration: 3600  # edita el tiempo en el que expira la sesión en segundos (1 hora)
  inactivity: 300   # edita el tiempo en el que detecte inactividad en segundo (5 minutos)
  domain: tudominio.com  # tu nombre de dominio. No es el subdominio.

regulation: # Intentos en un tiempo antes de ser baneado durante la duración que pongamos. En este caso si introduce 3 intentos erróneos en 10 minutos, serás baneado 12 horas.
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 # Base de datos que se crea con los usuarios.
  encryption_key: clavede20caracteres # Borrar el texto y sustituirlo por una cadena de 20 caracteres alternados con letras y números.

notifier:
  disable_startup_check: true #true/false
  smtp:
    username: tucorreo@gmail.com #tu usuario de correo
    password:  wich nmtv etxh abhr #Creamos una contraseña de aplicacion en google, la copiamos y la pegamos aquí
    host: smtp.gmail.com # servidor smtp, este es correcto si usas gmail
    port: 587 # puerto del servidor smtp, es este el que se utiliza si usas gmail
    sender: tucorreo@gmail.com # el correo de quien lo envia, poen el mismo que tu usuario
    identifier: localhost # No tocar
    subject: "[Authelia] {title}" # Asunto de los correos que enviará
